module.exports = {
    // EMOJIS //
    yesEmoji: "✅",
    noEmoji: "❌",
    linkEmoji: "🔗",
    partyEmoji: "🎉",
    artistEmoji: "👤",
    clockEmoji: "⏰",
    userEmoji: "👥",
    playEmoji: "▶️",
    pauseEmoji: "⏸️",
    loopEmoji: "🔁",
    shuffleEmoji: "🔀",
    previousEmoji: "⏮️",
    skipEmoji: "⏭️", 
    stopEmoji: "⏹️",
    rewind: "⏪",
    trashEmoji: "🗑️",
    volUpEmoji: "🔊",
    volDownEmoji: "🔉",
    listEmoji: "📋",
    infoEmoji: "ℹ️",
    musicEmoji: "🎵",
    warnEmoji: "⚠️",
    homeEmoji: "🏠",
    globeEmoji: "🌐",
    slashEmoji: "⚡",
    pingEmoji: "📶",
    questionEmoji: "❓",
    pencilEmoji: "✏️",
};